### ISSUE TITLE
Data is lost when exiting unexpectedly

### ISSUE THREAD

**Issue by yeldiRium** [NerdyPepper/dijo#58]
Dijo seems to only save its data when it is closed manually (using the q shortcut or the :quit command). If it is closed in any other way, all data since the start is lost.

I just rebooted my computer and lost data of the last 5-7 days. I'm not going to use dijo again.

But I wanted to open this issue nontheless to save others from my mistake and so that dijo can maybe overcome this limitation.

**Comment by NerdyPepper** [comment]
> Dijo seems to only save its data when it is closed manually

The [documentation](https://github.com/NerdyPepper/dijo/wiki/Commands#Commandline) is sparse around this, but you can save progress in two ways at the moment, with the `:write` command (save) and with the `:quit` command (save and quit).

> all data since the start is lost.

Data since the *last save* will be lost, if `dijo` does in fact deviate from this behavior, it might be worth opening another issue with your OS details, and the outputs of `rustc -v` and `dijo -V`.

---

If you are looking for an autosave feature, it has been requested over at the [feature thread](#10 ), but I am not too sold on the idea, `dijo`'s save behavior mimics that of other popular programs: `neovim`, `vim`, `cmus`, `weechat`.

**Comment by yeldiRium** [comment]
Thanks for the quick and complete answer :+1:
